### ISSUE TITLE
origen rc ci issue

### ISSUE THREAD

**Issue by jiangliu23** [Origen-SDK/origen#18]
I've encountered an issue today when commiting files to my own git branch, I was wondering if anyone else has ran into the same issue before, if so how did you manage to resolve it? please see the description of what happened to me below:

1. Ran 'rgen rc mods', two files were detected as modified (as expected)
2. Ran 'rgen rc ci', rgen correctly attempted to check in these two modified files.
3. Encounter a couple of pop-ups asking for freescale sw username and password before the check in process was complete, i made a typo when entering the password. So this forced the check-in process to quit.
4. then after this, it was not longer possible for rgen to detect any local modifications (even though on the sw site, there's no history of these two files being commited with my latest changes). everytime i run rgen rc mods, it just says my workspace is clean and nothing to commit. But the local changes are definitely there.

Below is was the error :

[INFO] 0.917[0.208] || On branch rainier_nexus
[INFO] 0.917[0.000] || Changes not staged for commit:
[INFO] 0.918[0.000] || (use "git add <file>..." to update what will be committed)
[INFO] 0.918[0.000] || (use "git checkout -- <file>..." to discard changes in working directory)
[INFO] 0.918[0.000] ||
[INFO] 0.918[0.000] || modified: target/calypso6M_n81m_nexus_ultraflex.rb
[INFO] 0.918[0.000] || modified: templates/web/partials/_navbar.html.erb
[INFO] 0.918[0.000] ||
[INFO] 0.918[0.000] || Untracked files:
[INFO] 0.918[0.000] || (use "git add <file>..." to include in what will be committed)
[INFO] 0.918[0.000] ||
[INFO] 0.918[0.000] || lib/soc/subpatterns/ultraflex/rainier2b_nexus_entry_old.atp
[INFO] 0.918[0.000] || lib/soc/subpatterns/ultraflex/rainier2b_nexus_entry_v0.atp
[INFO] 0.918[0.000] || lib/soc/subpatterns/ultraflex/rainier2b_nexus_entry_v1.PAT
[INFO] 0.918[0.000] || lib/soc/subpatterns/ultraflex/rainier2b_nexus_entry_v1.atp
[INFO] 0.918[0.000] || trans.log
[INFO] 0.918[0.000] ||
[INFO] 0.918[0.000] || no changes added to commit (use "git add" and/or "git commit -a")
[INFO] 0.926[0.008] || /pkg/OSS-git-/2.3.2/x86_64-linux/libexec/git-core/git-stash: line 530: eval_gettext: command not found
[INFO] 0.926[0.000] ||
[INFO] 0.943[0.017] || git reset HEAD
[INFO] 0.943[0.000] ||
[INFO] 0.987[0.044] || Unstaged changes after reset:
[INFO] 0.987[0.000] || M target/calypso6M_n81m_nexus_ultraflex.rb
[INFO] 0.987[0.000] || M templates/web/partials/_navbar.html.erb
[INFO] 0.987[0.000] || git add -u /proj/pet5/jiang/c55fx_nvm_tester_git
[INFO] 0.988[0.000] ||
[INFO] 1.109[0.122] || git commit -m "No comment!"
[INFO] 1.110[0.000] ||
[INFO] 1.174[0.064] || [rainier_nexus b263d08] No comment!
[INFO] 1.174[0.000] || 2 files changed, 12 insertions(+), 1 deletion(-)
[INFO] 1.197[0.023] || git push origin rainier_nexus
[INFO] 1.197[0.000] ||
[INFO] 8.242[7.045] || fatal: Authentication failed for 'http://sw-stash.freescale.net/scm/nvm/c55fx_nvm_tester.git/'
/home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/revision_control/git.rb:232:in `block (2 levels) in git': This command failed: 'git push origin rainier_nexus' (RGen::GitError)
from /pkg/fs-ruby-/2.1.5-p273/x86_64-linux/lib/ruby/2.1.0/open3.rb:199:in `popen_run'
from /pkg/fs-ruby-/2.1.5-p273/x86_64-linux/lib/ruby/2.1.0/open3.rb:188:in `popen2e'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/revision_control/git.rb:221:in `block in git'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/revision_control/git.rb:220:in `chdir'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/revision_control/git.rb:220:in `git'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/revision_control/git.rb:98:in `checkin'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/commands/rc.rb:283:in `<module:RGen>'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/commands/rc.rb:40:in `<top (required)>'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/commands.rb:178:in `require'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/lib/rgen/commands.rb:178:in `<top (required)>'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/bin/rgen:151:in `require'
from /home/b20251/.rgen/gems/ruby/2.1.0/gems/rgen_core-2.5.0.pre129/bin/rgen:151:in `<top (required)>'
from ./lbin/rgen:16:in `load'
from ./lbin/rgen:16:in `<main>'
[b20251@lvd0455 /proj/pet5/jiang/c55fx_nvm_tester_git $ ] rgen rc ci
No changes to check in
[b20251@lvd0455 /proj/pet5/jiang/c55fx_nvm_tester_git $ ] rgen rc mods
Checking for local modifications ...

Your workspace is clean

**Comment by ginty** [comment]
So the eventual state here was that the changes were checked in locally, but not pushed to the remote repo because of the user authentication error.

Once potential change improvement would be to make 'origen rc mods' return a warning if the local repo has updates which have not been pushed to the remote tracking branch.
