### ISSUE TITLE
Cannot create web documentation from on_flow_end callback

### ISSUE THREAD

**Issue by CodyBriscoe** [Origen-SDK/origen#222]
I'm trying to setup origen to automatically generate web documentation after generating a flow with the origen p command, so I added the following callback:

```
def on_flow_end(options)
  OrigenDocHelpers.generate_flow_docs layout: "#{Origen.root}/templates/web/layouts/_basic.html.erb", tab: :flows do |d|
    d.page  flow: "#{options[:test_module]}_flow".to_sym,
            name: "#{options[:test_module].to_s.upcase} Flow",
            target: "#{Origen.target.name}.rb"  
  end
end
```
This causes an error when building the flow page:
```
[INFO]       14.641[0.005]   || Building flow page: /users/chorton/osdk/ppekit/web/content/flows/pcie_flow.md

COMPLETE CALL STACK
-------------------
Can't find: partials/_navbar.html
/home/chorton/.origen/gems/ruby/2.3.0/bundler/gems/origen-7bf48a874995/lib/origen/file_handler.rb:137:in `clean_path_to'
/home/chorton/.origen/gems/ruby/2.3.0/bundler/gems/origen-7bf48a874995/lib/origen/file_handler.rb:226:in `rescue in clean_path_to_sub_template'
/home/chorton/.origen/gems/ruby/2.3.0/bundler/gems/origen-7bf48a874995/lib/origen/file_handler.rb:213:in `clean_path_to_sub_template'
/home/chorton/.origen/gems/ruby/2.3.0/bundler/gems/origen-7bf48a874995/lib/origen/generator/renderer.rb:8:in `render'
(erb):4:in `_get_binding'
```
There is no error if I separately call origen p (without the added callback) and then run: 
origen web compile --remote --api

Thanks

**Comment by coreyeng** [comment]
Hi @ginty, I pulled in this branch but I'm still seeing the spec fail:

~~~ruby
  1) Callbacks test of generating program documentation from on_flow_end callback
     Failure/Error: content = ERB.new(content, 0, Origen.config.erb_trim_mode, buffer).result(b)
                                                                                                
     NoMethodError:                                                                             
       undefined method `flow' for nil:NilClass                                                 
       Did you mean?  Float                               
~~~

I'm not seeing where the <code>MyCallbackDUT</code> is defined, so not sure if something is trying to use this and its getting the <code>NilClass</code> issue. This is missing somehow?

Full stack trace:

~~~
     NoMethodError:                                                                             
       undefined method `flow' for nil:NilClass                                                 
       Did you mean?  Float                                                                     
     # (erb):165:in `block in _get_binding'                                                     
     # (erb):164:in `each'                                                                      
     # (erb):164:in `_get_binding'                                                              
     # ./lib/origen/generator/compiler.rb:162:in `run_erb'                                      
     # ./lib/origen/generator/compiler.rb:55:in `compile'                                       
     # ./lib/origen/generator/renderer.rb:47:in `insert'                                        
     # ./lib/origen/generator/compiler.rb:164:in `run_erb'                                      
     # ./lib/origen/generator/compiler.rb:55:in `compile'                                       
     # ./lib/origen/generator/renderer.rb:47:in `insert'                                        
     # ./lib/origen/generator/compiler.rb:164:in `run_erb'                                      
     # ./lib/origen/generator/compiler.rb:35:in `compile_inline'                                
     # ./lib/origen.rb:569:in `compile'                                                         
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_doc_helpers-0.5.2/lib/origen_doc_helpers/flow_page_generator.rb:57:in `run'
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_doc_helpers-0.5.2/lib/origen_doc_helpers/flow_page_generator.rb:31:in `page'
     # ./spec/callbacks_spec.rb:161:in `block in on_flow_end'                                                                       
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_doc_helpers-0.5.2/lib/origen_doc_helpers/flow_page_generator.rb:18:in `run' 
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_doc_helpers-0.5.2/lib/origen_doc_helpers.rb:16:in `generate_flow_docs'      
     # ./spec/callbacks_spec.rb:160:in `on_flow_end'                                                                                
     # ./lib/origen/generator/flow.rb:46:in `block in create'                                                                       
     # ./lib/origen/generator/flow.rb:45:in `each'                                                                                  
     # ./lib/origen/generator/flow.rb:45:in `create'                                                                                
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_testers-0.16.1/lib/origen_testers/origen_ext/generator/flow.rb:41:in `create'
     # ./program/prb2.rb:3:in `<top (required)>'                                                                                     
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_testers-0.16.1/lib/origen_testers/generator.rb:19:in `load'                  
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_testers-0.16.1/lib/origen_testers/generator.rb:19:in `execute_source'        
     # ./lib/origen/generator/job.rb:134:in `run'                                                                                    
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_testers-0.16.1/lib/origen_testers/origen_ext/generator.rb:18:in `block in generate_program'
     # ./lib/origen/file_handler.rb:85:in `block in resolve_files'                                                                                 
     # ./lib/origen/file_handler.rb:71:in `each'                                                                                                   
     # ./lib/origen/file_handler.rb:71:in `resolve_files'                                                                                          
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_testers-0.16.1/lib/origen_testers/origen_ext/generator.rb:14:in `generate_program'         
     # ./lib/origen/application/runner.rb:81:in `block (2 levels) in launch'                                                                       
     # ./lib/origen/application/runner.rb:140:in `record_invocation'
     # ./lib/origen/application/runner.rb:75:in `block in launch'
     # ./lib/origen/file_handler.rb:393:in `preserve_state'
     # ./lib/origen/application/runner.rb:18:in `launch'
     # /home/b50956/.origen/gems/ruby/2.3.0/gems/origen_testers-0.16.1/lib/origen_testers/origen_ext/application/runner.rb:21:in `launch'
     # ./lib/origen/commands/program.rb:67:in `block in <top (required)>'
     # ./lib/origen/commands/program.rb:50:in `_with_doc_tester'
     # ./lib/origen/commands/program.rb:54:in `<top (required)>'
     # ./spec/callbacks_spec.rb:172:in `load'
     # ./spec/callbacks_spec.rb:172:in `block (2 levels) in <top (required)>'
     # ./config/commands.rb:19:in `<top (required)>'
     # ./lib/origen/commands.rb:183:in `require'
     # ./lib/origen/commands.rb:183:in `<top (required)>'
~~~

**Comment by CodyBriscoe** [comment]
Adding the `on_flow_end` no longer throws an error, however when defining the method defined in the OP, all that's generated is:
```
web/
`-- content
    |-- flows
    |   `-- pcie_flow.md
    `-- flows.md

2 directories, 2 files
```
where running `origen web compile` will generate html files among many others. Is this the expected behavior or should this callback also be generating html files?

**Comment by ginty** [comment]
This is the intended behaviour, the origen web compile command should turn
those into the final web pages.
