### ISSUE TITLE
Parameter set bug when default is used twice simultaneously

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#267]
Hi,

If I modify the default param set in the spec tests as follows:

~~~ruby
        define_params :default do |params|
          params.tprog = 20
          params.erase.time = 4
          params.erase.pulses = pulses
          params.test.ac.period = 10.ns
          params.test.func = -> { 2 * 2 }
          params.vdd.nom = 1
          params.vdd.min = 0.8
          params.vdd.max = 1.2
          params.measurement0.force_spec_val = "0.5A"
          params.measurement0.force_type = "SpecValue"
          params.measurement1.force_spec_val = "1.5A"
          params.measurement1.force_type = "SpecValue"
          params.default.default = 'whee'
        end
~~~

It seems to break the Parameter set API completely and all spec tests fail.

~~~shell
peologin07:origen $ bundle exec rspec spec/parameters_spec.rb

Parameters
  Parameters can be accessed via an explicit context (FAILED - 1)
  Min and max parameter names don't act funny (FAILED - 2)
  Defined values can be extracted (FAILED - 3)
  param sets cannot be re-opened (FAILED - 4)
  params cannot be modified or added outside of a define block (FAILED - 5)
  Works with local method calls in the defines (FAILED - 6)
  current param set can be changed (FAILED - 7)
  Setting the params to an unknown set will raise an error (FAILED - 8)
  inherited values work (FAILED - 9)
  with_params method works (FAILED - 10)
  function parameters work (FAILED - 11)
  live updating references can be created (FAILED - 12)
  Can bind to register bit values (FAILED - 13)
  inherited value works (FAILED - 14)
  parameter context can be proxied to dut (FAILED - 15)
  parameter context can be proxied to another object (FAILED - 16)
  parameter sets can be converted to a flat hash (FAILED - 17)
  retains proper hierarchy when converting to a flat hash (FAILED - 18)
  all available parameter contexts can be returned as an array (FAILED - 19)
  objects that own parameter sets can tell if they do or not (FAILED - 20)
  can pass inheritance between objects (FAILED - 21)
  params? can return value if exists, otherwise nil (FAILED - 22)
  cannot allow the last element in a parameter set to be set to false (FAILED - 23)

Failures:

  1) Parameters Parameters can be accessed via an explicit context
     Failure/Error: params.default.default = 'whee'

     NoMethodError:
       undefined method `default=' for nil:NilClass
     # ./spec/parameters_spec.rb:24:in `block in initialize'
     # ./lib/origen/parameters/set.rb:22:in `define'
     # ./lib/origen/parameters.rb:39:in `define_params'
     # ./spec/parameters_spec.rb:11:in `initialize'
     # ./lib/origen/model_initializer.rb:35:in `new'
     # ./spec/parameters_spec.rb:93:in `block (2 levels) in <module:ParametersSpec>'
~~~

I will poke around but if anyone has any ideas feel free.  If I change it to `params.myparam.default` it works.

thx

**Comment by info-rchitect** [comment]
Here is another case where using 'default' in the parameter set definition breaks.

~~~ruby
        define_params :binning_stds do |p|
          p.ws.default.bins = 19
          p.ws.default.softbins = :bbxxx
          p.ft.default.bins = 15
        end
~~~

Here is the error:

~~~shell
COMPLETE CALL STACK
-------------------
undefined method `bins=' for nil:NilClass
/users/user/origen/test/lib/test/test_modules/ddr_test_module.rb:35:in `block in define_default_params'
/users/user/origen/ruby/2.3.0/bundler/gems/origen-83fdbc9802ca/lib/origen/parameters/set.rb:22:in `define'
/users/user/origen/ruby/2.3.0/bundler/gems/origen-83fdbc9802ca/lib/origen/parameters.rb:39:in `define_params'
~~~

Here is the place where the error occurs:

~~~ruby
      def define(parent = nil, &_block)
        @defining = true
        begin
        yield self, parent
        rescue
          binding.pry
        end
        @defining = false
        finalize
      end
~~~

And here you can see the debugger info:

~~~ruby
[1] pry(#<Pry::Config>)> parent
=> nil
[2] pry(#<Pry::Config>)> self
=> {:ws=>{}}
[3] pry(#<Pry::Config>)> methods.grep(/default/)
=> [:copy_defaults_from, :default, :default=, :default_proc, :default_proc=]
~~~

I think this must be related to an existing method being named default and it being set to nil when this part of the parameter set definition is encountered.  

regards
