### ISSUE TITLE
Default target and environment seems to not work correctly

### ISSUE THREAD

**Issue by ginty** [Origen-SDK/origen#65]

**Comment by info-rchitect** [comment]
is this issue still open?  I am getting this error when trying the basic 'origen i' on gems built from the new command:

~~~shell
C:\origen\jironimo>origen i

COMPLETE CALL STACK
-------------------
undefined local variable or method `debug' for main:Object
C:/origen/jironimo/target/default.rb:1:in `<top (required)>'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/lib/origen/application.rb:775:in `load'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/lib/origen/application.rb:775:in `block in load_target!'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/lib/origen/application.rb:862:in `load_event'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/lib/origen/application.rb:765:in `load_target!'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/lib/origen/commands/interactive.rb:53:in `<module:Origen>'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/lib/origen/commands/interactive.rb:10:in `<top (required)>'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/lib/origen/commands.rb:222:in `require'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/lib/origen/commands.rb:222:in `<top (required)>'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/bin/origen:135:in `require'
C:/Users/bcaqueli/.origen/gems/ruby/2.2.0/bundler/gems/origen_for_dev-22681b701d49/bin/origen:135:in `<top (required)>'
C:/origen/jironimo/lbin/origen:17:in `load'
C:/origen/jironimo/lbin/origen:17:in `<main>'

APPLICATION CALL STACK
----------------------
undefined local variable or method `debug' for main:Object
C:/origen/jironimo/target/default.rb:1:in `<top (required)>'

C:\origen\jironimo>cat target/default.rb
debug.rb
C:\origen\jironimo>cat target/debug.rb
# Production mode will require that there are no modified files in the workspace
# and any other conditions that you add to your application.
# Normally production targets define the target and then debug targets
# are setup to load the production target before switching Origen to debug
# mode as shown below.
load "#{Origen.root}/target/production.rb"

Origen.mode = :debug

C:\origen\jironimo>cat target/production.rb
# The target file is run before *every* Origen operation and is used to instantiate
# the runtime environment - usually this means instantiating a top-level SoC or
# IP model.
#
# Naming is arbitrary but instances names should be prefixed with $ which indicates a
# global variable in Ruby, and this is required in order for the objects instantiated
# here to be visible throughout your application code.

$jira = Jironimo.launch  # Instantiate a JIRA client

~~~

As you can see, it doesn't seem to be gem related, rather it looks like it is putting 'debug.rb' in the default.rb target file.  What is the expected behavior regarding calling target files from within other target files?

**Comment by ginty** [comment]
I think this is still open, though I think what you are seeing here is #85
