### ISSUE TITLE
Ambiguous program file error is really a bug?

### ISSUE THREAD

**Issue by info-rchitect** [Origen-SDK/origen#93]
Hi,

As you can see below, I do not have 2 versions of the 'ws1.rb' program flow file.  Bug?

thx

~~~shell
peologin01:stp $ origen p ws1.rb
[INFO]       0.012[0.012]    || **********************************************************************
The following matches were found:
/home/username/origen/stp/program/ws1.rb
/home/username/origen/stp/program/ws1.rb

COMPLETE CALL STACK
-------------------
Ambiguous file ws1.rb
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/file_handler.rb:183:in `all_matches'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/file_handler.rb:123:in `clean_path_to'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/file_handler.rb:73:in `block in resolve_files'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/file_handler.rb:71:in `each'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/file_handler.rb:71:in `resolve_files'
/home/username/.origen/gems/ruby/2.3.0/gems/origen_testers-0.9.6/lib/origen_testers/origen_ext/generator.rb:14:in `generate_prog
ram'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/application/runner.rb:81:in `block (2 levels) in launch'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/application/runner.rb:140:in `record_invocation'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/application/runner.rb:75:in `block in launch'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/file_handler.rb:392:in `preserve_state'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/application/runner.rb:18:in `launch'
/home/username/.origen/gems/ruby/2.3.0/gems/origen_testers-0.9.6/lib/origen_testers/origen_ext/application/runner.rb:21:in `laun          ch'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/commands/program.rb:67:in `block in <top (required)>'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/commands/program.rb:50:in `_with_doc_tester'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/commands/program.rb:54:in `<top (required)>'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/commands.rb:222:in `require'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/lib/origen/commands.rb:222:in `<top (required)>'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/bin/origen:135:in `require'
/home/username/.origen/gems/ruby/2.3.0/gems/origen-0.20.1/bin/origen:135:in `<top (required)>'
/home/username/origen/stp/lbin/origen:17:in `load'
/home/username/origen/stp/lbin/origen:17:in `<main>'

APPLICATION CALL STACK
----------------------
Ambiguous file ws1.rb
peologin01:stp $ ls -alrt program/
total 24
drwxr-xr-x 20 username design 1024 Jun 28 12:00 ../
drwxr-xr-x  2 username design   80 Jun 28 12:00 components/
drwxr-xr-x  3 username design 1024 Jun 28 12:00 ./
-rw-r--r--  1 username design  118 Jun 28 12:00 ws1.rb
~~~

**Comment by ginty** [comment]
What do you have in the program directory, any other files with ws1 in the name?

**Comment by info-rchitect** [comment]
nothing, just the components directory and the ws1.rb file.  I will try to debug what is going on and make a PR if needed.

**Comment by ginty** [comment]
Seems to be a bug and I can reproduce it too, you can work around for now by doing:

~~~
origen p program/ws1.rb
~~~

**Comment by info-rchitect** [comment]
OK, simple bug I believe.  I put a comment in the code showing the line that should not be in the conditional.

~~~ruby
    def all_matches(file, options)
      if Origen.app.plugins.current
        matches = Dir.glob("#{options[:default_dir]}/#{Origen.app.plugins.current.name}/**/#{file}").sort
        matches = matches.flatten.uniq
        if matches.size == 0
          matches = Dir.glob("#{options[:default_dir]}/**/#{file}").sort
          matches = matches.flatten.uniq
        end
      else
        matches = (Dir.glob("#{options[:default_dir]}/**/#{file}") + # Avoids symlinks
                    Dir.glob("#{options[:default_dir]}/#{file}")).sort
        if matches.size == 0
          matches = Dir.glob("#{options[:default_dir]}/**{,/*/**}/#{file}").sort # Takes symlinks into consideration
          matches = matches.flatten.uniq # This line should not be part of the conditional
        end
      end
~~~

**Comment by ginty** [comment]
Great, please put it in a PR when you have time
